name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fed-docker-fnm:$(date +%s)
    - name: Create Folder
      run: mkdir -p ./app/ && mkdir -p ./pnpm_store
    - name: Test Docker image
      run: docker run -e PUID=$(id -u) -e PGID=$(id -g) -v $PWD/app:/app -v $PWD/pnpm_store:/config/pnpm_store -it fed-docker-fnm bash
