name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fed-docker-fnm:latest
    - name: Prepare Workspace
      run: git clone https://github.com/nailuoGG/taro-v4-template-starter.git app  && mkdir -p ./pnpm_store
    - name: Test Docker image
      run: docker run -e PUID=$(id -u) -e PGID=$(id -g) -v $PWD/app:/app -v $PWD/pnpm_store:/config/pnpm_store fed-docker-fnm:latest


  build-homelab:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fed-docker-fnm:latest
    - name: Prepare Workspace
      run: git clone https://github.com/nailuoGG/taro-v4-template-starter.git app  && mkdir -p ./pnpm_store
    - name: Test Docker image
      run: docker run -e PUID=$(id -u) -e PGID=$(id -g) -v $PWD/app:/app -v $PWD/pnpm_store:/config/pnpm_store fed-docker-fnm:latest
